package com.example.demo.model;

public class Books {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_name
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_quantity
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private Integer bookQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.press
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.price
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_name
     *
     * @return the value of books.book_name
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_name
     *
     * @param bookName the value for books.book_name
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_quantity
     *
     * @return the value of books.book_quantity
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public Integer getBookQuantity() {
        return bookQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_quantity
     *
     * @param bookQuantity the value for books.book_quantity
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setBookQuantity(Integer bookQuantity) {
        this.bookQuantity = bookQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.press
     *
     * @return the value of books.press
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.press
     *
     * @param press the value for books.press
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.price
     *
     * @return the value of books.price
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.price
     *
     * @param price the value for books.price
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}