package com.example.demo.model;

public class Classleader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.username
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.password
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.email
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.classid
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classleader.department
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.id
     *
     * @return the value of classleader.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.id
     *
     * @param id the value for classleader.id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.username
     *
     * @return the value of classleader.username
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.username
     *
     * @param username the value for classleader.username
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.password
     *
     * @return the value of classleader.password
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.password
     *
     * @param password the value for classleader.password
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.email
     *
     * @return the value of classleader.email
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.email
     *
     * @param email the value for classleader.email
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.classid
     *
     * @return the value of classleader.classid
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.classid
     *
     * @param classid the value for classleader.classid
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classleader.department
     *
     * @return the value of classleader.department
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classleader.department
     *
     * @param department the value for classleader.department
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}