package com.example.demo.model;

public class Grant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grant.order_id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grant.grant_time
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String grantTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grant.grant_place
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    private String grantPlace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grant.order_id
     *
     * @return the value of grant.order_id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grant.order_id
     *
     * @param orderId the value for grant.order_id
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grant.grant_time
     *
     * @return the value of grant.grant_time
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getGrantTime() {
        return grantTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grant.grant_time
     *
     * @param grantTime the value for grant.grant_time
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setGrantTime(String grantTime) {
        this.grantTime = grantTime == null ? null : grantTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grant.grant_place
     *
     * @return the value of grant.grant_place
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public String getGrantPlace() {
        return grantPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grant.grant_place
     *
     * @param grantPlace the value for grant.grant_place
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    public void setGrantPlace(String grantPlace) {
        this.grantPlace = grantPlace == null ? null : grantPlace.trim();
    }
}