package com.example.demo.mapper;

import com.example.demo.model.Books;
import com.example.demo.model.BooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    long countByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int deleteByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int insert(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int insertSelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    List<Books> selectByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    Books selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Books record, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByExample(@Param("record") Books record, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByPrimaryKeySelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByPrimaryKey(Books record);
}