package com.example.demo.mapper;

import com.example.demo.model.Grant;
import com.example.demo.model.GrantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GrantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    long countByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int deleteByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int insert(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int insertSelective(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    List<Grant> selectByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    Grant selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Grant record, @Param("example") GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByExample(@Param("record") Grant record, @Param("example") GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByPrimaryKeySelective(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grant
     *
     * @mbg.generated Tue Apr 28 01:33:54 CST 2020
     */
    int updateByPrimaryKey(Grant record);
}